### ISSUE TITLE
KeyError: 'tt0090564'

### ISSUE THREAD

**Issue by syedad218** [cryptexcode/folksonomication_source#2]
Traceback (most recent call last):
  File "train.py", line 260, in <module>
    test()
  File "train.py", line 248, in test
    loss, result = evaluate(model, test_generator)
  File "train.py", line 148, in evaluate
    for batch_idx, (word_sequence, emotion_vector, target_one_hot_vector, imdb_id) in enumerate(data_generator):
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/ubuntu/emotions/folksonomication_source/source/Dataset.py", line 19, in __getitem__
    word_sequence = torch.LongTensor(padded_sequence_list[imdb_id])
KeyError: 'tt0090564'
 
I have reprocessed the data using prepare data notebook still getting this error

**Comment by cryptexcode** [comment]
Can you please check if the features were extracted and loaded for this ID? Another issues was posted about this specific ID.

**Comment by syedad218** [comment]
--> As I can see, the emotion_score_dict_20_chunks file has an entry for ID:- tt0090564, but padded_word_sequences_1500 is not having an entry for this key coz for loop runs only for train_ids in process plot synopsis for loop whereas it runs for all_imdb_ids for the other.

--> Also I want to point out that prepare data notebook has max length=3000 for padded_word_sequence which gives matrix mismatch error while training, so I changed it back to 1500, now that error is gone.

--> One doubt I have is that the padded word sequences are all 1500 zeros not one of them is having any other number anywhere in that sequence, which I don't think should be happening.
Because most of them should be found in the word2idx dictionary. I changed the return statement of **pad_one_sequence function** from _return padded_sequence_ to _return padded_seq_ which is the correct one.

--> Please update the prepare data notebook with the latest one. 
--> This key  tt0090564 is a test id in the partition file.
--> Let me know if u want me to share my directory,  I can share it with u.

**Comment by syedad218** [comment]
it has been fixed so closing the issues now
